# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Ivan De Oliveira Nunes
tagline:          ''
description:      'Assistant Professor at RIT'
url:              ivan.csec.rit.edu
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:           
  name:           'Ivan De Oliveira Nunes'
  url:            https://twitter.com/ionunes

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
